# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Thinny
tagline:	'blog'
description:	'My personal blog.'
url:		www.wenshihang.top

author:
  name:		'Taylor Wen'
  url:		www.wenshihang.top

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/wenshihang20082
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/shihangwen
    desc:	Fork me on github

  - icon:	facebook
    url:	https://www.facebook.com/profile.php?id=100009824943160
    desc:	Add me on facebook

  - icon:	instagram
    url:	https://www.instagram.com/shihangwen/
    desc:	Follow me on instagram
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Taylor
  url:		www.wenshihang.top
  type_title:	Some rights reserved
